### ISSUE TITLE
change playing speed

### ISSUE THREAD

**Issue by 123liluky** [selimfirat/bilkent-video-annotation-tool#2]
What modification should I do in main.py to avoid changing into the next video automatically? Thank you. I want that a video is palyed again and again until 'pause' is clicked.

**Comment by selimfirat** [comment]
You may change 
`            if not self.isPaused:
                self.Stop()
                self.next()
` with some vlc library code to restart, which I do not remember at all.

Or via some hack, you may modify self.next method.  Removing
      `  self.current_video += 1` would remove changing into the next video. You may add a boolean flag to self.next and call with that on the code above to restart which does not increase the counter.


Additionally, if you make this change via an argparse argument, I would accept that pull request.

**Comment by 123liluky** [comment]
Thanks for your answer.
